version: "3.8"

services:
  newlife-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_OPENAI_KEY=${REACT_APP_OPENAI_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
